### ISSUE TITLE
Escape character '_' cannot be a safe character

### ISSUE THREAD

**Issue by mofanke** [jupyterhub/traefik-proxy#109]
`/usr/local/lib/python3.6/dist-packages/jupyterhub_traefik_proxy/traefik_utils.py:42: RuntimeWarning: Escape character '_' cannot be a safe character. Set allow_collisions=True if you want to allow ambiguous escaped strings.
return server_type + "_" + escapism.escape(routespec, safe=safe)
/usr/local/lib/python3.6/dist-packages/jupyterhub_traefik_proxy/consul.py:101: RuntimeWarning: Escape character '_' cannot be a safe character. Set allow_collisions=True if you want to allow ambiguous escaped strings.
escaped_target = escapism.escape(target, safe=self.key_safe_chars)
/usr/local/lib/python3.6/dist-packages/jupyterhub_traefik_proxy/consul.py:103: RuntimeWarning: Escape character '_' cannot be a safe character. Set allow_collisions=True if you want to allow ambiguous escaped strings.
jupyterhub_routespec, safe=self.key_safe_chars
`

**Comment by mofanke** [comment]
this is a warning all the time. i wonder whether we should handler this．
key_safe_chars = string.ascii_letters + string.digits + "!@#$%^&*();<>_-.+?:"
may be we can remove  "_" ?

**Comment by GeorgianaElena** [comment]
The problem is that we're adding the escape character (underscore) to the list of safe chars.

> key_safe_chars = string.ascii_letters + string.digits + "!@#$%^&*();<>-.+?:"

[These](https://github.com/jupyterhub/traefik-proxy/search?q=string.ascii_letters+%2B+string.digits+%2B&unscoped_q=string.ascii_letters+%2B+string.digits+%2B) are all the places that may cause that warning and from where we should remove the "_".

Do you want to make a PR to fix this :sunflower:  ?
