### ISSUE TITLE
What is the plan to release traefik v2 support 

### ISSUE THREAD

**Issue by trongchata** [jupyterhub/traefik-proxy#164]
The latest release tag still be 0.3.0, only support traefik v1.7
I saw there are lots of change to support latest Traefik v2 and etcd v3.  So when is the plan for next version release ?

Thanks

**Comment by minrk** [comment]
Hopefully soon. I think we've done most of the changes we need to. The big outstanding issues are #155 and #151, neither of which need to be addressed before a release with what we have so far.

I think we should probably finish #163, so we have a sense of our current situation re: performance, because when I try to stress the current branch I get lots of timeouts and failures (CHP can handle _far_ more transactions than traefik without failure).

Do you happen to use etcd or consul for your traefik deployment?

**Comment by trongchata** [comment]
The problem fixed, we have to setup
c.JupyterHub.bind_url = "https://:{port}"

In the traefik-proxy, it will use it to validate the entries response from traefik.

**Comment by minrk** [comment]
Yeah, I'm not sure we should be doing that check when traefik is run externally. I'll look into that.

**Comment by minrk** [comment]
If you'd like to test it, 1.0.0b1 is published: https://pypi.org/project/jupyterhub-traefik-proxy/1.0.0b1/

**Comment by minrk** [comment]
@alleny87 thanks for testing!

Can you run jupyterhub with `--debug` and share more of the logs? Also the logs of the traefik container with `--logging=debug`?

If the Hub and treafik are running in different containers, you do need to make sure that they are listening on _public_ ips within the container, and connecting to  hostnames connectable from other containers (typically the container name).

The two relevant config values are:

```python
# make sure the Hub is accessible from other containers
c.JupyterHub.hub_bind_url = 'http://:8000' 
# tell the hub where the proxy is
c.TraefikProxy.traefik_api_url = 'http://treafik-container-name:8099'
```

Also try disabling subdomain_host for now, as that adds complications to the routing while debugging.

> Any idea whats generating the error above?

My guess is it's the use of localhost, since the URLs don't appear to have been configured.

The 'SSL' part is a mistake in our log messages, since I didn't realize OSErrors could occur here without SSL set up, but the important part is 'cannot assign requested address', which seems weird to me in a connect call, but seems common in docker when connecting to localhost that shouldn't be used for some reason.

**Comment by chuckmandu** [comment]
Adding a rule to traefik to filter both localhost _and_ 127.0.0.1 for the api@internal service resolved the     

> asyncio.exceptions.TimeoutError: Traefik static configuration not available

 error for me (using Traefik 2.9.8 and Proxy 1.0.0b2.

That is:

```
[http.routers.traefik_api]
rule = "(Host(`127.0.0.1`) || Host(`localhost`)) && PathPrefix(`/api`)"
entryPoints = [ "traefik_api",]
service = "api@internal"
middlewares = [ "traefik_api",]
```

**Comment by minrk** [comment]
Thanks for testing and reporting back!

**Comment by minrk** [comment]
1.0 is out!
