### ISSUE TITLE
test with authenticated etcd server

### ISSUE THREAD

**Issue by minrk** [jupyterhub/traefik-proxy#18]
etcd in production is probably going to have credentials set up. We should test with an etcd server with authentication enabled to make sure that we have exposed the right configuration.

ref: https://coreos.com/etcd/docs/latest/v2/authentication.html

**Comment by GeorgianaElena** [comment]
@minrk, I'm not sure how to approach this issue. Should we rewrite the tests in `test_proxy.py` so that they pass for both an etcd with credentials set up and for one without?

I ran some experiments and realized that the asynchronous python etcd-client we use won't work as it is if we enable authentication for etcd. That's because before writing/reading keys to/from a credentials-enabled etcd, we first need to authenticate this client and make sure it has the right permissions for each operation.

Also, in order to enable etcd authentication, we need a `root` user and role. In my opinion, the root user should be the one that adds traefik's static configuration to etcd under the `/traefik/`prefix.
The dynamic configuration (the one we define through `proxy.add_route()`), is added under `/jupyterhub/` prefix and I believe it's better to add a separate role with rw permissions for this prefix and in this way we won't allow the users with this role to alter traefik's basic config.

Should the proxy be the one that sets-up the users and roles mentioned above in etcd? If so, how should the credentials be store? Also, if we want the tests to work on both authenticated and not authenticated etcd, what would be the best way to tell the proxy to enable or not the authentication without altering the public api (etcd doesn't have any mechanism of checking if the authentication is enabled or not, besides the errors it throws whenever you try to r/w keys to/from the store under no-user or under a user without the proper permissions)?

**Comment by minrk** [comment]
> Should the proxy be the one that sets-up the users and roles mentioned above in etcd?

I don't
I agree that it makes sense for those two things to be separate.

When we deploy this in practice on kubernetes, something else (the helm chart) is going to be responsible for the initial configuration, and only the add/remove routes is going to be used from here, so that makes sense.

> Should we rewrite the tests in test_proxy.py so that they pass for both an etcd with credentials set up and for one without?

I think we're going to want two kinds of tests:

1. generic tests that, given a configured Proxy instance, test the add/remove/etc. routing (this is #27). These tests won't talk to etcd directly or anything. Then what we can do is write a few different  setups that create the Proxy in different ways.
2. some lower-level tests that check implementation specifics (e.g. the tests that check with etcd directly)

Right now we have both kinds in `test_proxy`. Let's split it up so that the two kinds of tests are in two files (the etcd-specific ones in perhaps `test_etcd.py`), and then we can figure out how to run the same tests with a few different setups.

**Comment by minrk** [comment]
For whether auth is enabled or not, this should be configured on the proxy. e.g. if the user sets `TraefikEtcdProxy.etcd_password = 'secret'` that means auth is enabled. This can be checked with `if self.etcd_password:...` in the code.
