### ISSUE TITLE
Implement TraefikTOMLProxy

### ISSUE THREAD

**Issue by minrk** [jupyterhub/traefik-proxy#21]
Traefik can load config from both etcd and toml config files. We should include an implementation in `toml.py` of TraefikTOMLProxy that updates a traefik.toml config file. traefik already watches this config file for changes, so it should reload config as we write the file.

We need to be careful to make file updating atomic. It must:

- never allow concurrent reads and writes (use a mutex)
- never allow partial reads or writes (write a temp file and move it into place, rather than writing the file in place)

This should also be added to the entrypoints registered in setup.py as `traefik-toml`.

We will also likely want to make some of the tests we already have for etcd also run for this class, which might mean abstracting a bit some of the tests to run with different proxy implementations.

**Comment by GeorgianaElena** [comment]
@minrk, I am working on this issue and I have a couple of questions.

Do you think it's a good idea to keep a copy of the toml file in memory?
Otherwise each time we add a route for example we'll have to open the toml file, read it, find the appropriate line to add the new route and write all this to the temporary file.
It seems like a good idea to cache the toml file as this would avoid an unnecessary file read when adding a route. Also getting all the routes won't touch the disk.

Do you agree with having the routes in a separate toml file?
Traefik allows us to have one file for the static configuration (the `traefik.toml`) and one or several files for the routes, that traefik would watch. I believe keeping them separate would be cleaner (one file for all the routes though) and this would probably also help when somebody else will initialize the proxy.

**Comment by minrk** [comment]
> Do you think it's a good idea to keep a copy of the toml file in memory?

I think that's a great idea.

> Do you agree with having the routes in a separate toml file?

Let's try to sketch a few scenarios for when this could be used:

1. it's an extra file entirely managed outside
2. it's an extra file that jupyterhub is also responsible for

Based on this, I think what you've described makes sense: one file for just the routes, and one for the static configuration. Then, the difference is: when jupyterhub starts the proxy, it writes the static config once, then only edits the route config file. Similarly, when jupyterhub does not start the proxy, the user is totally responsible for the static config and jupyterhub is responsible exclusively for the routes. This should draw a clean line between what goes in each file.
