### ISSUE TITLE
Example outside of jupyterhub

### ISSUE THREAD

**Issue by Immortalin** [jupyterhub/traefik-proxy#53]
Would be nice to have an example that can show how sticky sessions and ips lead to dynamic routing etc.

**Comment by minrk** [comment]
I think there might be a misunderstanding here. `jupyterhub-traefik-proxy` is a plugin for using traefik with JupyterHub. It doesn't make sense to have an example outside JupyterHub.

**Comment by Immortalin** [comment]
I mean to use a Python API for controlling Traefik to do basic proxying without pulling in Jupyterhub dependencies.

**Comment by Immortalin** [comment]
Stuff like django-proxy do not have the performance of Traefik.

**Comment by minrk** [comment]
A generic Python API for managing traefik would be cool! That's not what this is, though, but if you find one then this could probably be simplified to build on that. Since everything here is about building on the Proxy base class from jupyterhub, it's not feasible to remove the jupyterhub dependency.
