### ISSUE TITLE
all traffic logs

### ISSUE THREAD

**Issue by nalui333** [jupyterhub/traefik-proxy#59]
Hi folks,

Is there a way to see all traffic logs incoming to jupyterhub. especially  at the onset during authentication.  As a note i'm launching traefik from jupyterhub so i can't use journalctl to view logs. Thanks

**Comment by GeorgianaElena** [comment]
Hi @nalui333! Thanks for opening this issue.

In order to see *all* JupyterHub logs, you can use the `--debug` option when  you start jupyterhub (more info about this [here](https://github.com/jupyterhub/jupyterhub/wiki/Debug-Jupyterhub) and [here](https://jupyterhub.readthedocs.io/en/stable/troubleshooting.html)). This debug flag will print all logs in console, including the TraefikProxy logs and logs about the authentication process.

By default, **traefik** (the routing "mechanism" used by JupyterHub TraefikProxy) only prints **ERROR** messages and unfortunately the log level isn't configurable if traefik is managed by JupyterHub (which is your case if I understand correctly).
It's probably a good idea to make this log level a configurable option, though :thinking: .

Let me know how it goes with the ``--debug`` and if TraefikProxy logs are enough to see what's going on with the proxy.

**Comment by nalui333** [comment]
Making it configurable would be awesome. I've been using jupyter --debug and i don't believe i'm seeing all the traffic on the wire hence my ask here.  I'm trying to kerberize jupyterhub and i'm trying to nail down what's being requested from the browser and what's been sent back and i'm not getting as much insight as i'd like so i know where the issues are. Thanks for your response.

**Comment by GeorgianaElena** [comment]
Unfortunately I don't think that another traefik log level will help either.
It looks you might need something like [wireshark](https://www.wireshark.org/)  or maybe even checkout your browser's dev tools (if you're using Firefox, checkout its [network monitor](https://developer.mozilla.org/ro/docs/Tools/Network_Monitor))
Have you tried any of these?

Also, can you please provide more info about the issue you're experiencing?

**Comment by nalui333** [comment]
essentially i'm trying to use the kerberos authenticator module to get a kerberos token passed to jupyterhub so that when it goes to spin up my use notebook environment the token is available to sparkmagic. This is required in order to use sparkmagic and livy to talk to a backend big data cluster. The stack works fine without kerberos but the org requires kerberization so ..... However i get a data None when i set debug statements in the kerberos authenticator module i'm using. I've trying using firefox monitor, i don't know if it's by design but i'm not seeing any of the spnego stuff. was goign to use tcpdump but don't have the privs here at the org will see if i can get a portable version of wireshark to work from the windows client side of things.

By the way i'm using https://github.com/jcrist/kerberosauthenticator/ as my auth module

**Comment by manics** [comment]
I'll close this since it sounds like the root problem is outside Traefik.
