### ISSUE TITLE
Distributed configuration problem

### ISSUE THREAD

**Issue by vhaldemar** [jupyterhub/traefik-proxy#71]
Hello!
I'm currently setuping distributed configuration where Jupyterhub working on one host, traefik and etcd are working at separate host/containers. Containters are stateless.
In near future I'm gonna add some additional traefik instances.
And now I have a problem: when container with etcd is redeploys, it loses all routes, and I need to tell the Hub to sync routes. 
At this point I have some complex bash-script, which is starts etcd and POST to `{hub_url}/api/proxy` (https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/proxy.py#L27)

With that in mind, I propose the following:
1) `jupyterhub_traefik_proxy` will contain special entry-point, something like `python -m jupyterhub_traefik_proxy.run_and_sync <path to traefik/etcd binary> --jupyterhub-url <...> --api-key <...>`
2) May be add tornado handler just like `ProxyAPIHandler`, to have `jupyterhub_traefik_proxy`-specific `PATCH` method to allow dynamicly relocate hosts with traefik.
3) Add documentation with examples about running traefik, etcd separately from JH.

Thank you!

**Comment by minrk** [comment]
Would it not be better to have etcd with a persistent volume to store data? That should eliminate the whole issue, no? Since we have the existing endpoint to poke jupyterhub to refresh the proxy and changing configuration (such as the traefik endpoint) requires Hub restart (which also ensures up-to-date routes in the proxy), I'm not sure how much there is to do here other than adding more detailed docs about running the kv store outside (including the strong recommendation that storage be persistent or hitting the proxy update endpoint upon known reset of the kv store).

**Comment by manics** [comment]
I'll close this since the solution is to enable persistent storage for the KV store.
